// products.js
export const products = [
    {
      id: 1,
      name: 'CMD',
      price: '฿100',
      imageSrc: 'https://i.namu.wiki/i/M2yw-kGZNnBi8LKwMHYYAZjjiyoxHEF1QqUG2lujFRPK9E6Nh-8PGvf-NsgIj-_WTEWNfqhl59BvFrOxgNtc_w.png',
      shopName: 'Shop 1',
    },
    {
      id: 2,
      name: 'excalibur',
      price: '฿200',
      imageSrc: 'https://www.metalbridges.com/wp-content/uploads/2015/02/Excalibur-sword-4cover.jpg',
      shopName: 'Shop 2',
    },
    {
      id: 3,
      name: 'ปืนใหญ่นีโออาร์มสตรอง',
      price: '฿150',
      imageSrc: 'https://f.ptcdn.info/507/031/000/1431956087-original-o.jpg',
      shopName: 'Shop 3',
    },
    {
      id: 4,
      name: 'Secret',
      price: '฿250',
      imageSrc: 'https://productmanagermeme.com/storage/assets/images/that-face-when-the-exec-team-comes-up-with-a-new-idea-1669616605.webp',
      shopName: 'Shop 4',
    },
    {
      id: 5,
      name: 'padoru',
      price: '฿300',
      imageSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsKwicrVmcyxC0HSYNXlDqZ6f39ae2n32q-g&s',
      shopName: 'Shop 5',
    },
    {
      id: 6,
      name: 'god of war',
      price: '฿400',
      imageSrc: 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png',
      shopName: 'Shop 6',
    },
    {
      id: 7,
      name: 'จุ๊บเหม่ง',
      price: '฿350',
      imageSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2YG2hP72L0gQXe7q_-51ciJGDnHVUeSQsxw&s',
      shopName: 'Shop 7',
    },
    {
      id: 8,
      name: 'minecraft bow',
      price: '฿450',
      imageSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbP77HbY5avui3CK1j07Xhc1i9zPR5BpfVr0VoOK_rcjcC98LLu0X_cMTM3Ss8-dNwSuA&usqp=CAU',
      shopName: 'Shop 8',
    },
    {
      id: 9,
      name: 'sigma',
      price: '฿500',
      imageSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI09C9-iWdZMVIKL7VhvjF9DbqljJI4jRYy8QO6uj3V0KOU5cAW2idKn2Kvznmpcbdg84&usqp=CAU',
      shopName: 'Shop 9',
    },
    {
      id: 10,
      name: 'tom and jerry',
      price: '฿600',
      imageSrc: 'https://us-fbcloud.net/quiz/data/48/48462.image2.jpg',
      shopName: 'Shop 10',
    },
    {
        id: 11,
        name: 'Man of Man',
        price: '฿600',
        imageSrc: 'https://us-fbcloud.net/quiz/data/43/43073.qst1.question.jpg',
        shopName: 'Shop 10',
      },
    {
        id: 12,
        name: 'ความเบียว',
        price: '฿600',
        imageSrc: 'https://i1.sndcdn.com/artworks-000034308557-3pv1yu-t500x500.jpg',
        shopName: 'Shop 10',
    }
  ];
